// Dummy data for visual testing outside market hours.
// Covers all visual states: ready, generating, unavailable, hopeful, sympathy,
// positive change, negative change, near-zero change.

import type { StockObject, HopefulResponse } from '../types';

export const DUMMY_STOCKS: StockObject[] = [
  {
    ticker: 'AMTX',
    sector: 'Hopeful',
    price: 2.84,
    changePercent: 34.21,
    zScore: 3.8,
    relVol: 6.2,
    isHopeful: true,
    isSympathy: false,
    parent: null,
    reason: 'DOE cellulosic ethanol grant triggered short squeeze on low float.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'MARA',
    sector: 'Hopeful',
    price: 18.40,
    changePercent: 12.10,
    zScore: 3.1,
    relVol: 4.8,
    isHopeful: true,
    isSympathy: false,
    parent: null,
    reason: 'Bitcoin rally driving crypto miner momentum on above average volume.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'GEVO',
    sector: 'Hopeful',
    price: 1.92,
    changePercent: 8.40,
    zScore: 2.7,
    relVol: 3.9,
    isHopeful: false,
    isSympathy: true,
    parent: 'AMTX',
    reason: 'Sympathy move following AMTX DOE grant.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'RIOT',
    sector: 'Hopeful',
    price: 9.20,
    changePercent: 6.30,
    zScore: 2.6,
    relVol: 2.8,
    isHopeful: false,
    isSympathy: true,
    parent: 'MARA',
    reason: 'Sympathy with MARA on Bitcoin rally.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'NVDA',
    sector: 'Technology',
    price: 876.20,
    changePercent: 2.84,
    zScore: 2.9,
    relVol: 3.1,
    isHopeful: false,
    isSympathy: false,
    parent: null,
    reason: 'Beat Q4 EPS by 18%, raised FY guidance.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'TSLA',
    sector: 'Consumer',
    price: 245.12,
    changePercent: -1.82,
    zScore: 2.1,
    relVol: 2.4,
    isHopeful: false,
    isSympathy: false,
    parent: null,
    reason: 'Analyst downgrade on margin compression.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'AAPL',
    sector: 'Technology',
    price: 189.45,
    changePercent: 1.20,
    zScore: 1.4,
    relVol: 1.1,
    isHopeful: false,
    isSympathy: false,
    parent: null,
    reason: '',
    reasonStatus: 'generating',
  },
  {
    ticker: 'SOFI',
    sector: 'Financials',
    price: 8.92,
    changePercent: 5.40,
    zScore: 2.8,
    relVol: 3.3,
    isHopeful: false,
    isSympathy: false,
    parent: null,
    reason: 'Student loan refinancing demand beat analyst estimates significantly.',
    reasonStatus: 'ready',
  },
  {
    ticker: 'PLTR',
    sector: 'Technology',
    price: 24.80,
    changePercent: -2.10,
    zScore: 2.2,
    relVol: 2.2,
    isHopeful: false,
    isSympathy: false,
    parent: null,
    reason: 'No catalyst found',
    reasonStatus: 'unavailable',
  },
  {
    ticker: 'XOM',
    sector: 'Energy',
    price: 118.30,
    changePercent: 0.84,
    zScore: 0.9,
    relVol: 0.9,
    isHopeful: false,
    isSympathy: false,
    parent: null,
    reason: 'WTI crude up on supply drawdown data.',
    reasonStatus: 'ready',
  },
];

// See ARCHITECTURE.md §10.3 — leaders + sympathy split for Hopeful tab.
export const DUMMY_HOPEFUL: HopefulResponse = {
  leaders: DUMMY_STOCKS.filter((s) => s.isHopeful && !s.isSympathy),
  sympathy: DUMMY_STOCKS.filter((s) => s.isSympathy),
};
